name: "PyInstaller Linux AMD64"
description: "GitHub Action package, Your python code to Binary for Linux AMD64 Architecture"
branding:
  icon: "box"
  color: "blue"
inputs:
  path:
    description: "Directory containing source code & .spec file (optional requirements.txt)."
    required: True
    default: src
  pypi_url:
    description: "Specify a custom URL for PYPI"
    required: False
    default: https://pypi.python.org/
  pypi_index_url:
    description: "Specify a custom URL for PYPI Index"
    required: False
    default: https://pypi.python.org/simple
  spec:
    description: "Specify a file path for .spec file"
    required: False
    default: ""
  requirements:
    description: 'Specify a file path for requirements.txt file'
    required: False
    default: "requirements.txt"
  rename:
    description: 'Rename the binary file, this will only work when you have --onefile binary.'
    required: False
    default: ""
outputs:
  location:
    description: 'Binary file location.'
  filename:
    description: 'Binary file name.'
  content_type:
    description: 'File content type.'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.pypi_url }}
    - ${{ inputs.pypi_index_url }}
    - ${{ inputs.spec }}
    - ${{ inputs.requirements }}
    - ${{ inputs.rename }}
